### ISSUE TITLE
Контейнер с улучшениями

### ISSUE THREAD

**Issue by JoyZzzzz** [kyzima-spb/antizapret#2]
Попробовал ваш  контейнер с улучшениями, но некоторые сайты которые работали в стандартном антизапрете перестали открываться. Путь заворачиваеться в контейнер, но дальше сайт не открывается.
И подскажите в чем в вашем контейнере улучшения по сравнению со стандартным?

**Comment by kyzima-spb** [comment]
В стандартном - это который они предлагают самостоятельно установить?

По второму вопросу, я добавлял для удобства некоторые правки:

1. Фиксил русскую кодировку в доменах, т.к. с определенного момента контейнер перестал работать при чистой установке (возможно сейчас они это уже пофиксили)
2. Фиксил OpenNIC, чтобы IP адреса не были жестко забиты в конфиг файле, а парсились с оф сайта, НО, не особо понял этой альтернативной зоны, несмотря на заведомо рабочие IP, сайты могут не открываться, либо могут открыться, а через минуту уже нет, не пользуюсь в итоге =)
3. Были какие-то проблемы с добавлением своих хостов в include-hosts-custom.txt, не заворачивало в контейнер, как оказалось, эти хосты были изначально указаны в файле exclude-что-то-там, как игнорируемые
4. Сделал так, чтобы файл include-hosts-custom.txt объединялся с тем что уже добавлено и моим списком, который я в гит пушу, мне так удобнее, чем каждый раз на сервер бежать
5. Я помню, что ставил пакеты, которых не хватало, socat, например, не был доступен в контейнере

Вообще я хотел на более свежий Debian обновиться, но увы, не получилось

**Comment by kyzima-spb** [comment]
Хотя стоп, это было в первой версии, потом что-то у меня не работало так, как я ожидал и я все переделывал и к тому моменту русские символы уже были пофиксены "из коробки", так что первый пункт не в счет =)
