### ISSUE TITLE
Прокси антизапрет на домашнем сервере

### ISSUE THREAD

**Issue by jastden** [kyzima-spb/antizapret#3]
Возможно ли использовать данное ПО на своем домашнем сервере например с Proxmox или в Docker, что бы все клиенты в сети имели доступ к заблокированным сайтам?

**Comment by kyzima-spb** [comment]
Официальный "образ" антизапрета в Docker запустить не возможно, потому что он использует systemd. На форуме встречалась ссылка на альтернативный вариант, но я его не проверял - https://github.com/xtrime-ru/antizapret-vpn-docker

С Proxmox не знаком =)

На домашнем я думаю запустить можно, если установить в контейнер клиент для вашего vpn и чтобы контейнер всегда был подключен к vpn-у. Я думал о таком варианте, но он кажется каким-то костыльным, хотя имеет ряд плюсов =)

Можете еще поискать ответ на форуме автора - https://ntc.party/t/контейнер-vpn-антизапрета-для-установки-на-собственный-сервер/, по любому такой вопрос уже возникал у кого-нибудь =)

Если хочется обход блокировок дома, я бы смотрел вот такое - https://itdog.info/tochechnaya-marshrutizaciya-po-domenam-na-routere-s-openwrt/
